### ISSUE TITLE
make fails on Android

### ISSUE THREAD

**Issue by rapkin61** [jfriesse/omping#42]
$ make
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O addrfunc.c -o addrfunc.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O aiifunc.c -o aiifunc.o
In file included from aiifunc.c:37:
In file included from ./omping.h:25:
In file included from ./rhfunc.h:33:
./gcra.h:43:52: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
extern int              gcra_rl(struct gcra_item *item, struct timeval tv);
                                                               ^
In file included from aiifunc.c:37:
In file included from ./omping.h:25:
./rhfunc.h:72:17: error: field has incomplete type 'struct timeval'
        struct timeval  last_init_ts;
                        ^
./util.h:55:15: note: forward declaration of 'struct timeval'
extern struct timeval   util_get_time(void);
              ^
In file included from aiifunc.c:37:
In file included from ./omping.h:25:
./rhfunc.h:73:17: error: field has incomplete type 'struct timeval'
        struct timeval  last_query_ts;
                        ^
./util.h:55:15: note: forward declaration of 'struct timeval'
extern struct timeval   util_get_time(void);
              ^
In file included from aiifunc.c:37:
In file included from ./omping.h:25:
./rhfunc.h:101:18: error: field has incomplete type 'struct timeval'
        struct timeval          last_init_ts;
                                ^
./util.h:55:15: note: forward declaration of 'struct timeval'
extern struct timeval   util_get_time(void);
              ^
1 warning and 3 errors generated.
make: *** [Makefile:41: aiifunc.o] Error 1

$ uname -a
Linux localhost 4.14.113-26023986 #1 SMP PREEMPT Thu Apr 27 09:44:28 +07 2023 aarch64 Android

**Comment by jfriesse** [comment]
Hi,
thank you for the issue. Could you please try add_time_h_for_timeval branch (https://github.com/jfriesse/omping/tree/add_time_h_for_timeval) or commit https://github.com/jfriesse/omping/commit/e6adebb59450f573a9fe258d6e616af429953c73 ?

**Comment by rapkin61** [comment]
that works perfect, trank you!

~ $ git clone --branch add_time_h_for_timeval   https://github.com/jfriesse/omping.git
Cloning into 'omping'...
remote: Enumerating objects: 664, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 664 (delta 2), reused 1 (delta 0), pack-reused 658
Receiving objects: 100% (664/664), 175.84 KiB | 4.51 MiB/s, done.
Resolving deltas: 100% (479/479), done.
~ $ cd omping/
~/omping $ make
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O addrfunc.c -o addrfunc.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O aiifunc.c -o aiifunc.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O cli.c -o cli.o
cli.c:141:44: warning: implicit conversion from 'uint64_t' (aka 'unsigned long') to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-const-int-float-conversion]
                        if (numd < 1 || *ep != '\0' || numd >= ((uint64_t)~0)) {
                                                            ~~  ^~~~~~~~~~~~
1 warning generated.
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O cliprint.c -o cliprint.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O clisig.c -o clisig.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O clistate.c -o clistate.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O gcra.c -o gcra.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O logging.c -o logging.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O msg.c -o msg.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O msgsend.c -o msgsend.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O omping.c -o omping.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O rhfunc.c -o rhfunc.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O rsfunc.c -o rsfunc.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O sfset.c -o sfset.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O sockfunc.c -o sockfunc.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O tlv.c -o tlv.o
cc -c -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O util.c -o util.o
cc -Wall -Wshadow -Wp,-D_FORTIFY_SOURCE=2 -g -O  addrfunc.o aiifunc.o cli.o cliprint.o clisig.o clistate.o \
    gcra.o logging.o msg.o msgsend.o omping.o rhfunc.o rsfunc.o sfset.o sockfunc.o \
    tlv.o util.o -o omping

**Comment by jfriesse** [comment]
Perfect, thank you for confirmation! I've also noticed the warning produced by compiler. Could you please try to compile again with updated branch (I've added patch  https://github.com/jfriesse/omping/commit/f37ba8afc8669a19b6aa4e2650cb601a2a193e38) ? Thanks.

**Comment by jfriesse** [comment]
I've merged both patches as a e2aca77282ec802395a1eb76d9e23d08be8076c5 . Thank you for the report!
